# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sd_store', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plinth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('printer', models.CharField(max_length=5)),
                ('pi_ip', models.GenericIPAddressField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.Deployment')),
            ],
        ),
        migrations.CreateModel(
            name='SensorPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='sd_store.Sensor')),
            ],
        ),
    ]
