# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mac_address', models.CharField(max_length=255)),
                ('external_network_address', models.GenericIPAddressField(blank=True, null=True)),
                ('network_address', models.GenericIPAddressField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hub_images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubConnectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('online_since', models.DateTimeField(blank=True, null=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('hub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_status_object', to='hubs.Hub')),
            ],
            options={
                'verbose_name_plural': 'Hub connection statuses',
            },
        ),
    ]
