# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentannotation',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Deployment'),
        ),
    ]
